env: "local" #local, dev, prod
storage_address: "postgresql://postgres:157315@localhost:5433/urlshortener"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "alex"
  password: "1234"